name: krk_stops_app
description: KrkStops application

publish_to: 'none'

version: 1.20.0+49

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  protobuf: ^5.0.0
  cupertino_http: ^2.3.0
  http: ^1.1.0
  shared_preferences: ^2.5.0
  url_launcher: ^6.0.2
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  protoc_plugin: ^23.0.0
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true
  generate: true
